simpleInputDialogを修正 fixed #34
actlaboratory/NPC pull request #35
Opened 2023-01-22 00:21 UTC by kitabatake1013

複数行入力をした際、2行目以降が失われる（1行目しか取得できない）問題を修正しました。
validationPatternとマッチするかどうかの確認については、この機能を使っている箇所や用途がわからず、動作を確認できていません。

2023-01-22 00:34 UTC, yamahubuki requested changes
この書き方だと、バリデーションは各行に対して働きます。
その場合は空白行を無視してあげないとつらそうに思います。

2023-01-22 00:35 UTC, yamahubuki commented
そして、どこか1行でも合わなければバリデーションを失敗扱いにする必要がありそうです。

2023-04-23 03:48 UTC, kitabatake1013 commented
修正しました。
よろしくお願いします。

2023-04-23 09:36 UTC, yamahubuki approved these changes

2023-04-23 09:36 UTC, merged